import {
  LayoutDashboard,
  ShoppingBag,
  UtensilsCrossed,
  Tags,
  QrCode,
  Users,
  Gift,
  UserCog,
  BarChart3,
  Settings,
  Package,
  Map,
  ClipboardList,
  ShieldCheck,
  BadgePercent,
  Star,
  Bell,
  CreditCard,
  Dices,
  UsersRound,
  Megaphone,
} from "lucide-react";
import { ROUTE_PATH } from "./routePaths";

export const MENU_ITEMS = [
  { key: "dashboard", label: "Dashboard", icon: LayoutDashboard, path: ROUTE_PATH.DASHBOARD },

  { type: "header", key: "grp-sales", label: "Bán hàng & Vận hành" },
  { key: "orders", label: "Đơn hàng", icon: ShoppingBag, path: ROUTE_PATH.ORDERS },
  { key: "menu", label: "Menu", icon: UtensilsCrossed, path: ROUTE_PATH.MENU },
  { key: "categories", label: "Danh mục", icon: Tags, path: ROUTE_PATH.CATEGORIES },
  { key: "zones", label: "Khu vực", icon: Map, path: ROUTE_PATH.ZONES },
  { key: "tables", label: "Bàn & QR", icon: QrCode, path: ROUTE_PATH.TABLES },
  { key: "shifts", label: "Ca làm việc", icon: ClipboardList, path: ROUTE_PATH.SHIFTS },
  { key: "payments", label: "Thanh toán", icon: CreditCard, path: ROUTE_PATH.PAYMENTS },

  { type: "header", key: "grp-inventory", label: "Kho vận" },
  { key: "inventory", label: "Kho & Nguyên liệu", icon: Package, path: ROUTE_PATH.INVENTORY },

  { type: "header", key: "grp-crm", label: "CRM & Marketing" },
  { key: "customers", label: "Khách hàng", icon: Users, path: ROUTE_PATH.CUSTOMERS },
  { key: "segments", label: "Nhóm khách hàng", icon: UsersRound, path: ROUTE_PATH.SEGMENTS },
  { key: "campaigns", label: "Chiến dịch", icon: Megaphone, path: ROUTE_PATH.CAMPAIGNS },
  { key: "loyalty", label: "Loyalty & Events", icon: Gift, path: ROUTE_PATH.LOYALTY },
  { key: "promotions", label: "Khuyến mãi", icon: BadgePercent, path: ROUTE_PATH.PROMOTIONS },
  { key: "reviews", label: "Đánh giá", icon: Star, path: ROUTE_PATH.REVIEWS },
  { key: "notifications", label: "Thông báo", icon: Bell, path: ROUTE_PATH.NOTIFICATIONS },
  { key: "lucky-wheel", label: "Vòng quay may mắn", icon: Dices, path: ROUTE_PATH.LUCKY_WHEEL },

  { type: "header", key: "grp-admin", label: "Quản trị" },
  { key: "staff", label: "Nhân viên", icon: UserCog, path: ROUTE_PATH.STAFF },
  { key: "roles", label: "Vai trò & Quyền", icon: ShieldCheck, path: ROUTE_PATH.ROLES },
  { key: "reports", label: "Báo cáo", icon: BarChart3, path: ROUTE_PATH.REPORTS },
  { key: "settings", label: "Cài đặt", icon: Settings, path: ROUTE_PATH.SETTINGS },
];
