export const UNIT_OPTIONS = [
  { value: "g", label: "gram (g)" },
  { value: "ml", label: "mililít (ml)" },
  { value: "cái", label: "cái" },
  { value: "kg", label: "kilogram (kg)" },
  { value: "lít", label: "lít" },
];

export const TEXT = {
  pageTitle: "Kho & Nguyên liệu",
  pageDesc: "Quản lý nguyên liệu, tồn kho và cảnh báo tồn thấp.",
  addItem: "Thêm nguyên liệu",
  searchPlaceholder: "Tìm theo tên nguyên liệu...",
  colName: "Nguyên liệu",
  colUnit: "Đơn vị",
  colStock: "Tồn kho",
  colMinStock: "Tồn tối thiểu",
  colCost: "Giá vốn/đơn vị",
  colStatus: "Trạng thái",
  colActions: "Thao tác",
  viewDetail: "Xem chi tiết",
  edit: "Chỉnh sửa",
  delete: "Xóa",
  confirmDeleteTitle: "Xác nhận xóa nguyên liệu",
  confirmDeleteDesc: (name) => `Bạn có chắc muốn xóa "${name}"?`,
  confirmYes: "Xóa",
  confirmNo: "Hủy",
  lowStock: "Tồn thấp",
  inStock: "Đủ tồn",
  detailTitle: "Chi tiết nguyên liệu",
  editTitle: "Chỉnh sửa nguyên liệu",
  createTitle: "Thêm nguyên liệu",
  back: "Quay lại",
  save: "Lưu thay đổi",
  cancel: "Hủy",
};
