export const ALL_CATEGORIES = "__all__";

export const TEXT = {
  pageTitle: "Thực đơn",
  pageDesc: "Quản lý danh sách món, giá và trạng thái.",
  addItem: "Thêm món",
  searchPlaceholder: "Tìm theo tên món...",
  allCategories: "Tất cả danh mục",
  colName: "Tên món",
  colCategory: "Danh mục",
  colPrice: "Giá bán",
  colStock: "Tồn kho",
  colStatus: "Trạng thái",
  colActions: "Thao tác",
  viewDetail: "Xem chi tiết",
  edit: "Chỉnh sửa",
  delete: "Ngừng bán / Xóa",
  confirmDeleteTitle: "Ngừng kinh doanh / Ẩn món",
  confirmDeleteDesc: (name) =>
    `Bạn có chắc muốn ngừng bán và ẩn món "${name}"? Món sẽ được chuyển sang trạng thái ngưng kinh doanh và ẩn khỏi thực đơn của cửa hàng.`,
  confirmYes: "Xác nhận",
  confirmNo: "Huỷ",
  createTitle: "Thêm món mới",
  detailTitle: "Chi tiết món",
  editTitle: "Chỉnh sửa món",
  fieldName: "Tên món",
  fieldCategory: "Danh mục",
  fieldPrice: "Giá bán (đ)",
  fieldStock: "Tồn kho",
  fieldImage: "Ảnh (URL hoặc Public ID)",
  fieldDescription: "Mô tả",
  fieldStatus: "Trạng thái",
  back: "Quay lại",
  save: "Lưu thay đổi",
  create: "Tạo mới",
  cancel: "Huỷ",
  notFound: "Không tìm thấy món này.",
  loadError: "Không tải được dữ liệu.",
  empty: "Chưa có món nào.",
};
