import { PRODUCT_STATUS } from "@/constants/application";

export const MOCK_MENU_ITEMS = [
  {
    id: "menu-001",
    name: "Cà phê đen",
    category: "coffee",
    price: 25000,
    description: "Cà phê đen truyền thống, đậm đà hương vị",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-10T08:00:00.000Z",
  },
  {
    id: "menu-002",
    name: "Cà phê sữa",
    category: "coffee",
    price: 30000,
    description: "Cà phê sữa đặc trưng, ngọt ngào",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-10T08:00:00.000Z",
  },
  {
    id: "menu-003",
    name: "Cappuccino",
    category: "coffee",
    price: 55000,
    description: "Espresso kết hợp với sữa tươi và bọt sữa mịn",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-11T08:00:00.000Z",
  },
  {
    id: "menu-004",
    name: "Latte",
    category: "coffee",
    price: 60000,
    description: "Espresso với nhiều sữa tươi, vị nhẹ nhàng",
    status: PRODUCT_STATUS.INACTIVE,
    image: null,
    createdAt: "2024-01-11T08:00:00.000Z",
  },
  {
    id: "menu-005",
    name: "Trà đào cam sả",
    category: "tea",
    price: 45000,
    description: "Trà đào kết hợp cam và sả, thanh mát",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-12T08:00:00.000Z",
  },
  {
    id: "menu-006",
    name: "Trà vải",
    category: "tea",
    price: 45000,
    description: "Trà xanh kết hợp vải tươi, hương thơm dịu",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-12T08:00:00.000Z",
  },
  {
    id: "menu-007",
    name: "Trà chanh",
    category: "tea",
    price: 35000,
    description: "Trà chanh truyền thống, chua ngọt",
    status: PRODUCT_STATUS.OUT_OF_STOCK,
    image: null,
    createdAt: "2024-01-13T08:00:00.000Z",
  },
  {
    id: "menu-008",
    name: "Trà sữa trân châu",
    category: "tea",
    price: 55000,
    description: "Trà sữa Đài Loan với trân châu đen dẻo",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-13T08:00:00.000Z",
  },
  {
    id: "menu-009",
    name: "Bánh mì bơ",
    category: "food",
    price: 25000,
    description: "Bánh mì nướng bơ thơm giòn",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-14T08:00:00.000Z",
  },
  {
    id: "menu-010",
    name: "Croissant",
    category: "food",
    price: 45000,
    description: "Bánh sừng bò nhập khẩu, giòn xốp",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-14T08:00:00.000Z",
  },
  {
    id: "menu-011",
    name: "Bánh flan caramel",
    category: "food",
    price: 35000,
    description: "Bánh flan mềm mịn với lớp caramel đắng nhẹ",
    status: PRODUCT_STATUS.INACTIVE,
    image: null,
    createdAt: "2024-01-15T08:00:00.000Z",
  },
  {
    id: "menu-012",
    name: "Nước cam tươi",
    category: "other",
    price: 40000,
    description: "Cam vắt tươi 100%, không đường",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-15T08:00:00.000Z",
  },
  {
    id: "menu-013",
    name: "Sinh tố bơ",
    category: "other",
    price: 50000,
    description: "Bơ xay với sữa đặc, béo ngậy",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-16T08:00:00.000Z",
  },
  {
    id: "menu-014",
    name: "Nước dừa",
    category: "other",
    price: 35000,
    description: "Nước dừa tươi nguyên chất",
    status: PRODUCT_STATUS.OUT_OF_STOCK,
    image: null,
    createdAt: "2024-01-16T08:00:00.000Z",
  },
  {
    id: "menu-015",
    name: "Mocha",
    category: "coffee",
    price: 65000,
    description: "Espresso kết hợp sô-cô-la và sữa tươi",
    status: PRODUCT_STATUS.ACTIVE,
    image: null,
    createdAt: "2024-01-17T08:00:00.000Z",
  },
];
